apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: kinesis-firehose-sink-connector
  namespace: myproject
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.aws2kinesisfirehose.CamelAws2kinesisfirehoseSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: kinesis-firehose-topic
    camel.sink.path.streamName: firehose-stream
    camel.component.aws2-s3.accessKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws2-kinesis-firehose-cred.properties:accessKey}
    camel.component.aws2-s3.secretKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws2-kinesis-firehose-cred.properties:secretKey}
    camel.component.aws2-s3.region: ${file:/opt/kafka/external-configuration/aws-credentials/aws2-kinesis-firehose-cred.properties:region}
