= Camel-Kafka-connector AWS2 KMS Sink for deleting a key

This is an example for Camel-Kafka-connector AWS2-KMS Sink for deleting a key

== Standalone

=== What is needed

- An AWS Account

=== Running Kafka

[source]
----
$KAFKA_HOME/bin/zookeeper-server-start.sh $KAFKA_HOME/config/zookeeper.properties
$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties
$KAFKA_HOME/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic mytopic
----

=== Download the connector package

Download the connector package tar.gz and extract the content to a directory. In this example we'll use `/home/oscerd/connectors/`

[source]
----
> cd /home/oscerd/connectors/
> wget https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-aws2-kms-kafka-connector/0.11.5/camel-aws2-kms-kafka-connector-0.11.5-package.tar.gz
> untar.gz camel-aws2-kms-kafka-connector-0.11.5-package.tar.gz
----

=== Configuring Kafka Connect

You'll need to set up the `plugin.path` property in your kafka

Open the `$KAFKA_HOME/config/connect-standalone.properties` and set the `plugin.path` property to your choosen location:

[source]
----
...
plugin.path=/home/oscerd/connectors
...
----

=== Setup the connectors

Open the AWS2 KMS configuration file at `$EXAMPLES/aws2-kms/aws2-kms-sink-delete-key/config/CamelAWS2KMSSinkConnector.properties`

[source]
----
name=CamelAWS2KMSSinkConnector
connector.class=org.apache.camel.kafkaconnector.aws2kms.CamelAws2kmsSinkConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

topics=mytopic

camel.sink.path.label=kms-point

camel.component.aws2-kms.operation=scheduleKeyDeletion

camel.component.aws2-kms.accessKey=<accessKey>
camel.component.aws2-kms.secretKey=<secretKey>
camel.component.aws2-kms.region=<region>
----

and add the correct credentials for AWS.

=== Running the example

Run the kafka connect with the KMS Sink connector:

[source]
----
$KAFKA_HOME/bin/connect-standalone.sh $KAFKA_HOME/config/connect-standalone.properties $EXAMPLES/aws2-kms/aws2-kms-sink-delete-key/config/CamelAWS2KMSSinkConnector.properties
----

On a different terminal run the kafkacat producer and send the following message

[source]
----
> echo "Test1" | ./kafkacat -b localhost:9092 -t mytopic -H "CamelHeader.CamelAwsKMSKeyId=<id>"
----

On your AWS KMS console, you should see the key related to id scheduled for deletion.
